# Generated by Django 6.1 on 2026-08-19 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('crm', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=120, null=True)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=160, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=160, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=160, null=True)),
                ('referrer_domain', models.CharField(blank=True, max_length=250, null=True)),
                ('landing_path', models.CharField(max_length=500)),
                ('device_category', models.CharField(blank=True, max_length=30, null=True)),
                ('consent_state', models.CharField(max_length=30)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_sessions', to='crm.lead')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='analytics.anonymousvisitor')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(db_index=True, max_length=80)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('page_path', models.CharField(blank=True, max_length=500, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('listing_public_key', models.UUIDField(blank=True, null=True)),
                ('listing_title_snapshot', models.CharField(blank=True, max_length=240, null=True)),
                ('development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.development')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='crm.lead')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='listings.listing')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.propertyoffering')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='analytics.anonymousvisitor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='analytics.websession')),
            ],
            options={
                'permissions': [('view_bi', 'Puede consultar información de negocio')],
            },
        ),
        migrations.AddIndex(
            model_name='websession',
            index=models.Index(fields=['visitor', 'started_at'], name='analytics_w_visitor_5c1427_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_name', '-occurred_at'], name='analytics_a_event_n_cef4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session', 'occurred_at'], name='analytics_a_session_1e854d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['listing', 'occurred_at'], name='analytics_a_listing_7d7264_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['offering', 'occurred_at'], name='analytics_a_offerin_03dfd1_idx'),
        ),
    ]
