# Generated by Django 6.1 on 2026-08-19 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('common', '0001_initial'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugRedirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_path', models.CharField(max_length=500, unique=True)),
                ('new_path', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=170, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('offering', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='listing', to='catalog.propertyoffering')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('publish_listing', 'Puede publicar propiedades'), ('unpublish_listing', 'Puede despublicar propiedades'), ('archive_listing', 'Puede archivar propiedades'), ('restore_listing', 'Puede restaurar propiedades'), ('hard_delete_listing', 'Puede eliminar propiedades definitivamente')],
            },
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HERO', 'Portada'), ('GALLERY', 'Galería'), ('FLOORPLAN', 'Plano'), ('DOCUMENT', 'Documento')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='listings.listing')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media_library.mediaasset')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_type', models.CharField(choices=[('FIXED', 'Precio fijo'), ('FROM', 'Desde'), ('RANGE', 'Rango'), ('ON_REQUEST', 'Precio a consultar')], max_length=15)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.propertyoffering')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.sourcerecord')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('TEMPORARILY_UNAVAILABLE', 'No disponible temporalmente'), ('RESERVED', 'Reservada'), ('SOLD', 'Vendida')], max_length=30)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_history', to='catalog.propertyoffering')),
            ],
            options={
                'indexes': [models.Index(fields=['offering', '-effective_from'], name='listings_av_offerin_ffdacf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('offering',), name='one_current_availability_per_offering')],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_published', 'archived_at'], name='listings_li_is_publ_a25061_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['published_at'], name='listings_li_publish_32106c_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['offering', '-effective_from'], name='listings_pr_offerin_a330ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('offering',), name='one_current_price_per_offering'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount_min__gte', 0), ('amount_min__isnull', True), _connector='OR'), name='price_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount_max__gte', 0), ('amount_max__isnull', True), _connector='OR'), name='price_max_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_max__isnull', True), ('amount_min__isnull', True), ('price_type', 'ON_REQUEST')), models.Q(('price_type', 'ON_REQUEST'), _negated=True), _connector='OR'), name='on_request_has_no_amount'),
        ),
    ]
