# Generated by Django 6.1 on 2026-08-21 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_propertyoffering_amenities_and_more'),
        ('common', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricerecord',
            name='on_request_has_no_amount',
        ),
        migrations.AddConstraint(
            model_name='availabilityrecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'TEMPORARILY_UNAVAILABLE', 'RESERVED', 'SOLD'])), name='availability_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrecord',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__gt', models.F('effective_from')), ('effective_to__isnull', True), _connector='OR'), name='availability_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(('price_type__in', ['FIXED', 'FROM', 'RANGE', 'ON_REQUEST'])), name='price_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount_max__gte', models.F('amount_min')), ('amount_max__isnull', True), ('amount_min__isnull', True), _connector='OR'), name='price_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_max__isnull', True), ('amount_min__isnull', True), ('price_type', 'ON_REQUEST')), models.Q(('amount_min__isnull', False), ('price_type__in', ['FIXED', 'FROM'])), models.Q(('amount_max__isnull', False), ('amount_min__isnull', False), ('price_type', 'RANGE')), _connector='OR'), name='price_amounts_match_type'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__gt', models.F('effective_from')), ('effective_to__isnull', True), _connector='OR'), name='price_period_valid'),
        ),
    ]
