# Generated by Django 6.1 on 2026-08-21 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_propertyoffering_offering_bedrooms_max_nonnegative_and_more'),
        ('common', '0001_initial'),
        ('listings', '0002_remove_pricerecord_on_request_has_no_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerecord',
            name='currency',
            field=models.CharField(choices=[('MXN', 'Peso mexicano')], default='MXN', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'MXN')), name='price_currency_mxn'),
        ),
    ]
