# Generated by Django 6.1 on 2026-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_pricerecord_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerecord',
            name='promotion_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='promotion_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='promotion_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='promotion_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
