# Generated by Django 6.1 on 2026-08-19 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('OFFICIAL_WEBSITE', 'Sitio oficial'), ('BROCHURE', 'Folleto'), ('VISIT', 'Visita'), ('INVENTORY_LIST', 'Lista de inventario'), ('MANUAL', 'Captura manual'), ('OTHER', 'Otra')], max_length=24)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
