# Generated by Django 6.1 on 2026-08-21 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def move_featured_location_content(apps, schema_editor):
    municipality_model = apps.get_model("geo", "Municipality")
    content_model = apps.get_model("content", "LocationContent")
    for municipality in municipality_model.objects.filter(is_featured=True):
        base = slugify(municipality.name) or "ubicacion"
        slug = base if not content_model.objects.filter(slug=base).exists() else f"{base}-{str(municipality.id)[:8]}"
        content_model.objects.get_or_create(
            municipality=municipality,
            defaults={"slug": slug, "is_featured": True, "description": ""},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('geo', '0002_municipality_is_featured'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(max_length=230, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hero_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_heroes', to='media_library.mediaasset')),
                ('municipality', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='location_content', to='geo.municipality')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(move_featured_location_content, migrations.RunPython.noop),
    ]
