# Generated by Django 6.1 on 2026-08-24 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_locationcontent'),
        ('listings', '0003_alter_pricerecord_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('eyebrow_override', models.CharField(blank=True, max_length=120, null=True)),
                ('title_override', models.CharField(blank=True, max_length=240, null=True)),
                ('subtitle_override', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hero_slides', to='content.homecontent')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_hero_slides', to='listings.listing')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('home_content', 'listing'), name='unique_home_listing_slide')],
            },
        ),
    ]
