# Generated by Django 6.1 on 2026-09-10 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sitesettings'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='CasaViva', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='commercial_role',
            field=models.CharField(default='EXTERNAL_PROMOTER', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='commercial_role_display',
            field=models.CharField(default='Promotor externo', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='complaints_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='operator_type',
            field=models.CharField(default='PERSONA_FISICA', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='responsible_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='responsible_name',
            field=models.CharField(default='José Alfredo Salazar Hernández', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='verification_warning_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(default='main', max_length=40, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('hero_title', models.CharField(max_length=240)),
                ('main_title', models.CharField(max_length=240)),
                ('main_body', models.TextField()),
                ('what_we_do_title', models.CharField(max_length=240)),
                ('what_we_do_body', models.TextField()),
                ('how_we_work_title', models.CharField(max_length=240)),
                ('how_we_work_body', models.TextField()),
                ('vision_title', models.CharField(max_length=240)),
                ('vision_body', models.TextField()),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hero_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_heroes', to='media_library.mediaasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
