# Generated by Django 6.1 on 2026-09-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_sitesettings_brand_name_sitesettings_commercial_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'permissions': [('manage_legal_identity', 'Puede administrar la identidad legal de CasaViva')]},
        ),
    ]
