# Generated by Django 6.1 on 2026-08-19 17:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('category', models.CharField(choices=[('DEVELOPMENT', 'Desarrollo'), ('INTERIOR', 'Interior'), ('EXTERIOR', 'Exterior'), ('SERVICE', 'Servicio')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('BOOLEAN', 'Sí / No'), ('NUMBER', 'Número'), ('TEXT', 'Texto'), ('CHOICE', 'Opción')], max_length=12)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('legal_name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('logo_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_logos', to='media_library.mediaasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_developers', 'Puede administrar desarrolladoras')],
            },
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('street_address', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='developments', to='catalog.developer')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.locality')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.municipality')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.neighborhood')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_developments', 'Puede administrar desarrollos')],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.amenity')),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.development')),
            ],
        ),
        migrations.AddField(
            model_name='development',
            name='amenities',
            field=models.ManyToManyField(blank=True, through='catalog.DevelopmentAmenity', to='catalog.amenity'),
        ),
        migrations.CreateModel(
            name='DevelopmentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HERO', 'Portada'), ('GALLERY', 'Galería'), ('FLOORPLAN', 'Plano'), ('DOCUMENT', 'Documento')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='catalog.development')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media_library.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalog.featuredefinition')),
            ],
        ),
        migrations.CreateModel(
            name='HousingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('internal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=230, unique=True)),
                ('base_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housing_models', to='catalog.developer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_models', 'Puede administrar modelos')],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('display_name_override', models.CharField(blank=True, max_length=180, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_links', to='catalog.development')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('housing_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_links', to='catalog.housingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(choices=[('DEVELOPER', 'Desarrolladora'), ('PRIVATE', 'Particular')], max_length=20)),
                ('variant_name', models.CharField(blank=True, max_length=180, null=True)),
                ('street_address', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bedrooms_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bedrooms_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bathrooms_total', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('full_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('half_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('levels_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('levels_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('construction_area_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('construction_area_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('construction_area_basis', models.CharField(blank=True, choices=[('EXACT', 'Exacta'), ('UP_TO', 'Hasta'), ('FROM', 'Desde'), ('RANGE', 'Rango'), ('UNKNOWN', 'Desconocida')], max_length=10, null=True)),
                ('land_area_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_area_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_area_basis', models.CharField(blank=True, choices=[('EXACT', 'Exacta'), ('UP_TO', 'Hasta'), ('FROM', 'Desde'), ('RANGE', 'Rango'), ('UNKNOWN', 'Desconocida')], max_length=10, null=True)),
                ('garden_area_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('garden_area_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('garden_area_basis', models.CharField(blank=True, choices=[('EXACT', 'Exacta'), ('UP_TO', 'Hasta'), ('FROM', 'Desde'), ('RANGE', 'Rango'), ('UNKNOWN', 'Desconocida')], max_length=10, null=True)),
                ('internal_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('default_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('development_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.developmentmodel')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.locality')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.municipality')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.neighborhood')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.propertytype')),
            ],
            options={
                'permissions': [('manage_offerings', 'Puede administrar propiedades'), ('manage_catalogs', 'Puede administrar catálogos')],
            },
        ),
        migrations.CreateModel(
            name='OfferingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HERO', 'Portada'), ('GALLERY', 'Galería'), ('FLOORPLAN', 'Plano'), ('DOCUMENT', 'Documento')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media_library.mediaasset')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='catalog.propertyoffering')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferingFeatureValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.featuredefinition')),
                ('value_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.featurechoice')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='catalog.propertyoffering')),
            ],
        ),
        migrations.CreateModel(
            name='OfferingAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.amenity')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_links', to='catalog.propertyoffering')),
            ],
        ),
        migrations.AddConstraint(
            model_name='developmentamenity',
            constraint=models.UniqueConstraint(fields=('development', 'amenity'), name='unique_development_amenity'),
        ),
        migrations.AddIndex(
            model_name='development',
            index=models.Index(fields=['developer'], name='catalog_dev_develop_f8f62a_idx'),
        ),
        migrations.AddIndex(
            model_name='development',
            index=models.Index(fields=['state', 'municipality'], name='catalog_dev_state_i_0b6fa5_idx'),
        ),
        migrations.AddConstraint(
            model_name='featurechoice',
            constraint=models.UniqueConstraint(fields=('definition', 'value'), name='unique_feature_choice_value'),
        ),
        migrations.AddIndex(
            model_name='housingmodel',
            index=models.Index(fields=['developer', 'archived_at'], name='catalog_hou_develop_4c4bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentmodel',
            index=models.Index(fields=['development', 'housing_model'], name='catalog_dev_develop_00c1ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='developmentmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('development', 'housing_model'), name='unique_active_development_model'),
        ),
        migrations.AddConstraint(
            model_name='offeringfeaturevalue',
            constraint=models.UniqueConstraint(fields=('offering', 'definition'), name='unique_offering_feature'),
        ),
        migrations.AddConstraint(
            model_name='offeringamenity',
            constraint=models.UniqueConstraint(fields=('offering', 'amenity'), name='unique_offering_amenity'),
        ),
        migrations.AddIndex(
            model_name='propertyoffering',
            index=models.Index(fields=['development_model'], name='catalog_pro_develop_976850_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyoffering',
            index=models.Index(fields=['property_type'], name='catalog_pro_propert_70c1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyoffering',
            index=models.Index(fields=['state', 'municipality'], name='catalog_pro_state_i_8e5a53_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyoffering',
            index=models.Index(fields=['property_type', 'bedrooms_min', 'bathrooms_total'], name='catalog_pro_propert_851eb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('development_model__isnull', False), ('source_type', 'DEVELOPER')), models.Q(('development_model__isnull', True), ('source_type', 'PRIVATE')), _connector='OR'), name='offering_source_requires_relation'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms_min__gte', 0), ('bedrooms_min__isnull', True), _connector='OR'), name='offering_bedrooms_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('bathrooms_total__gte', 0), ('bathrooms_total__isnull', True), _connector='OR'), name='offering_bathrooms_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('default_commission_rate__gte', 0), ('default_commission_rate__isnull', True), _connector='OR'), name='offering_commission_nonnegative'),
        ),
    ]
