# Generated by Django 6.1 on 2026-08-21 07:46

from django.conf import settings
from django.db import migrations, models


def backfill_condition(apps, schema_editor):
    offering = apps.get_model("catalog", "PropertyOffering")
    offering.objects.filter(source_type="DEVELOPER", condition__isnull=True).update(condition="NEW")
    offering.objects.filter(source_type="PRIVATE", condition__isnull=True).update(condition="USED")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('geo', '0002_municipality_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffering',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='offerings', through='catalog.OfferingAmenity', to='catalog.amenity'),
        ),
        migrations.AddField(
            model_name='propertyoffering',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'Nueva'), ('USED', 'Usada')], max_length=10, null=True),
        ),
        migrations.RunPython(backfill_condition, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('default_commission_rate__lte', 100), ('default_commission_rate__isnull', True), _connector='OR'), name='offering_commission_max_100'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__range', (-90, 90)), ('latitude__isnull', True), _connector='OR'), name='offering_latitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__range', (-180, 180)), ('longitude__isnull', True), _connector='OR'), name='offering_longitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms_max__gte', models.F('bedrooms_min')), ('bedrooms_max__isnull', True), ('bedrooms_min__isnull', True), _connector='OR'), name='offering_bedrooms_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('parking_max__gte', models.F('parking_min')), ('parking_max__isnull', True), ('parking_min__isnull', True), _connector='OR'), name='offering_parking_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('levels_max__gte', models.F('levels_min')), ('levels_max__isnull', True), ('levels_min__isnull', True), _connector='OR'), name='offering_levels_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('construction_area_min__gte', 0), ('construction_area_min__isnull', True), _connector='OR'), name='offering_construction_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('construction_area_max__gte', 0), ('construction_area_max__isnull', True), _connector='OR'), name='offering_construction_max_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('construction_area_max__gte', models.F('construction_area_min')), ('construction_area_max__isnull', True), ('construction_area_min__isnull', True), _connector='OR'), name='offering_construction_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('land_area_min__gte', 0), ('land_area_min__isnull', True), _connector='OR'), name='offering_land_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('land_area_max__gte', 0), ('land_area_max__isnull', True), _connector='OR'), name='offering_land_max_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('land_area_max__gte', models.F('land_area_min')), ('land_area_max__isnull', True), ('land_area_min__isnull', True), _connector='OR'), name='offering_land_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('garden_area_min__gte', 0), ('garden_area_min__isnull', True), _connector='OR'), name='offering_garden_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('garden_area_max__gte', 0), ('garden_area_max__isnull', True), _connector='OR'), name='offering_garden_max_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('garden_area_max__gte', models.F('garden_area_min')), ('garden_area_max__isnull', True), ('garden_area_min__isnull', True), _connector='OR'), name='offering_garden_range_valid'),
        ),
    ]
