# Generated by Django 6.1 on 2026-08-21 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_propertyoffering_amenities_and_more'),
        ('geo', '0002_municipality_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms_max__gte', 0), ('bedrooms_max__isnull', True), _connector='OR'), name='offering_bedrooms_max_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('parking_min__gte', 0), ('parking_min__isnull', True), _connector='OR'), name='offering_parking_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('parking_max__gte', 0), ('parking_max__isnull', True), _connector='OR'), name='offering_parking_max_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('levels_min__gte', 0), ('levels_min__isnull', True), _connector='OR'), name='offering_levels_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='propertyoffering',
            constraint=models.CheckConstraint(condition=models.Q(('levels_max__gte', 0), ('levels_max__isnull', True), _connector='OR'), name='offering_levels_max_nonnegative'),
        ),
    ]
