# Generated by Django 6.1 on 2026-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_propertyoffering_offering_bedrooms_max_nonnegative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffering',
            name='information_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyoffering',
            name='internal_source_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyoffering',
            name='promotion_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyoffering',
            name='public_provider_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
