# Generated by Django 6.1 on 2026-08-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycode',
            name='code_hash',
            field=models.CharField(max_length=256),
        ),
    ]
