# Generated by Django 6.1 on 2026-08-24 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_direct_permissions(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    PermissionOverride = apps.get_model("accounts", "PermissionOverride")
    for user in User.objects.prefetch_related("user_permissions"):
        permissions = list(user.user_permissions.all())
        PermissionOverride.objects.bulk_create([
            PermissionOverride(user_id=user.pk, permission_id=permission.pk, effect="ALLOW")
            for permission in permissions
        ])
        if permissions:
            user.user_permissions.clear()


def restore_direct_permissions(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    PermissionOverride = apps.get_model("accounts", "PermissionOverride")
    for user in User.objects.all():
        permission_ids = PermissionOverride.objects.filter(user_id=user.pk, effect="ALLOW").values_list("permission_id", flat=True)
        user.user_permissions.add(*permission_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_recoverycode_code_hash'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effect', models.CharField(choices=[('ALLOW', 'Permitir'), ('DENY', 'Denegar')], max_length=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casaviva_overrides', to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'permission'), name='unique_user_permission_override')],
            },
        ),
        migrations.RunPython(migrate_direct_permissions, restore_direct_permissions),
    ]
