"use client";

import { useCallback, useEffect, useState } from "react";
import { AdminLayout, AdminTable } from "@/components/admin";
import { apiFetch, fetchAllPages } from "@/services/api";
import { formatCurrency, formatDate, slugify } from "@/lib/utils";

type BiData = {
  current: Record<string, number>; previous: Record<string, number>;
  traffic: Array<{ date: string; sessions: number; visitors: number }>;
  funnel: Array<{ label: string; value: number }>;
  funnel_description?: string;
  lead_cohort?: { leads: number; with_visit: number; with_closed_sale: number };
  inventory: Record<string, number>;
};

const labels: Record<string, string> = { visitors: "Visitantes", sessions: "Sesiones", listing_views: "Propiedades vistas", inquiries: "Consultas", visits_scheduled: "Visitas programadas", visits_completed: "Visitas realizadas", visits_cancelled: "Canceladas", visits_no_show: "No asistió", sales: "Ventas cerradas" };

export function AdminBiPage() {
  const [days, setDays] = useState(30);
  const [data, setData] = useState<BiData>();
  const [searches, setSearches] = useState<any>(); const [marketing, setMarketing] = useState<any>({ campaigns: [], creatives: [], sales_by_origin: [] }); const [sales, setSales] = useState<any>(); const [decisions, setDecisions] = useState<any>();
  const [error, setError] = useState("");
  useEffect(() => { apiFetch<BiData>(`/api/v1/admin/bi/overview/?days=${days}`).then(setData).catch((e) => setError(e.message)); }, [days]);
  useEffect(() => { Promise.all([apiFetch<any>(`/api/v1/admin/bi/searches/?days=${days}`), apiFetch<any>(`/api/v1/admin/bi/marketing/?days=${days}&horizon=90`), apiFetch<any>(`/api/v1/admin/bi/sales/?days=${days}`), apiFetch<any>(`/api/v1/admin/bi/decisions/?days=${days}`)]).then(([a,b,c,d]) => { setSearches(a); setMarketing(b); setSales(c); setDecisions(d); }).catch((e) => setError(e.message)); }, [days]);
  const maxTraffic = Math.max(1, ...(data?.traffic.map((x) => x.sessions) || [1]));
  return <AdminLayout title="Business Intelligence">
    <div className="admin-title"><div><span className="eyebrow">Resultados</span><h2>Resumen ejecutivo</h2></div><label className="period-select">Periodo<select value={days} onChange={(e) => setDays(Number(e.target.value))}><option value="7">7 días</option><option value="30">30 días</option><option value="90">90 días</option></select></label></div>
    {error && <p className="form-error">{error}</p>}
    <div className="metric-grid">{data && Object.entries(labels).map(([key, label]) => <div className="metric-card" key={key}><span>{label}</span><strong>{data.current[key] || 0}</strong><small>Periodo anterior: {data.previous[key] || 0}</small></div>)}</div>
    <div className="admin-panels">
      <section className="admin-panel"><h3>Tráfico en el tiempo</h3><div className="bi-bars" aria-label="Sesiones por día">{data?.traffic.map((x) => <div key={x.date} title={`${x.date}: ${x.sessions} sesiones`}><span style={{ height: `${Math.max(3, x.sessions / maxTraffic * 100)}%` }} /><small>{new Date(x.date).getDate()}</small></div>)}</div></section>
      <section className="admin-panel"><h3>Actividad por etapa</h3><p className="muted">{data?.funnel_description}</p><div className="bi-funnel">{data?.funnel.map((x) => <div key={x.label}><span>{x.label}</span><strong>{x.value}</strong></div>)}</div>{data?.lead_cohort && <><h3>Cohorte de clientes del periodo</h3><div className="inventory-line"><span>Clientes creados <strong>{data.lead_cohort.leads}</strong></span><span>Con visita <strong>{data.lead_cohort.with_visit}</strong></span><span>Con venta cerrada <strong>{data.lead_cohort.with_closed_sale}</strong></span></div></>}</section>
    </div>
    <section className="admin-panel"><h3>Inventario</h3><div className="inventory-line"><span>Registradas <strong>{data?.inventory.registered || 0}</strong></span><span>Publicadas <strong>{data?.inventory.published || 0}</strong></span><span>No publicadas <strong>{data?.inventory.unpublished || 0}</strong></span><span>Archivadas <strong>{data?.inventory.archived || 0}</strong></span></div></section>
    <ListingPerformance days={days} />
    <div className="admin-panels"><section className="admin-panel"><h3>Búsquedas por ubicación</h3><p className="muted">Búsquedas sin resultados: {searches?.no_results || 0}</p><div className="bi-funnel">{searches?.municipalities?.map((x: any) => <div key={x.label}><span>{x.label}</span><strong>{x.count}</strong></div>)}</div></section><section className="admin-panel"><h3>Filtros más usados</h3><div className="bi-funnel">{searches?.filters?.map((x: any) => <div key={x.label}><span>{x.label}</span><strong>{x.count}</strong></div>)}</div></section></div>
    <section className="admin-panel bi-table"><h3>Adquisición por campaña</h3><p className="muted">Clientes adquiridos en el periodo y su resultado posterior a 90 días. Atribución: primera sesión conocida.</p><AdminTable heads={["Campaña", "Sesiones", "Clientes", "Consultas", "Visitas realizadas", "Ventas cerradas", "Gasto", "Costo por venta"]}>{marketing.campaigns?.map((x: any) => <tr key={x.utm_campaign}><td>{x.utm_campaign}</td><td>{x.sessions}</td><td>{x.leads}</td><td>{x.inquiries}</td><td>{x.completed_visits}</td><td>{x.closed_sales}</td><td>{x.spend == null ? "—" : formatCurrency(Number(x.spend))}</td><td>{x.cost_per_sale == null ? "—" : formatCurrency(Number(x.cost_per_sale))}</td></tr>)}</AdminTable></section>
    <section className="admin-panel bi-table"><h3>Contenido y fuente</h3><p className="muted">Desglose de actividad y conversiones. El gasto no se reparte entre contenidos cuando sólo existe a nivel campaña.</p><AdminTable heads={["Fuente", "Medio", "Contenido", "Sesiones", "Vistas", "Consultas", "Visitas realizadas", "Ventas"]}>{marketing.creatives?.map((x: any) => <tr key={[x.utm_source,x.utm_medium,x.utm_campaign,x.utm_content].join("|")}><td>{x.utm_source || "Directo"}</td><td>{x.utm_medium || "—"}</td><td>{x.utm_content || "—"}</td><td>{x.sessions}</td><td>{x.views}</td><td>{x.inquiries}</td><td>{x.completed_visits}</td><td>{x.closed_sales}</td></tr>)}</AdminTable></section>
    <section className="admin-panel bi-table"><h3>Ventas cerradas en el periodo por origen</h3><p className="muted">Parte de la fecha de cierre y recupera la primera fuente conocida del cliente, aunque la adquisición ocurriera antes.</p><AdminTable heads={["Campaña", "Fuente", "Medio", "Ventas", "Valor", "Comisión"]}>{marketing.sales_by_origin?.map((x: any, index: number) => <tr key={`${x.utm_campaign}-${index}`}><td>{x.utm_campaign || "Sin campaña"}</td><td>{x.utm_source || "Directo"}</td><td>{x.utm_medium || "—"}</td><td>{x.closed_sales}</td><td>{formatCurrency(Number(x.revenue))}</td><td>{formatCurrency(Number(x.commission))}</td></tr>)}</AdminTable></section>
    <section className="admin-panel"><h3>Ventas por periodo</h3><div className="inventory-line"><span>Ventas <strong>{sales?.totals?.sales || 0}</strong></span><span>Valor <strong>{sales?.totals?.value == null ? "—" : formatCurrency(Number(sales.totals.value))}</strong></span><span>Comisiones <strong>{sales?.totals?.commissions == null ? "—" : formatCurrency(Number(sales.totals.commissions))}</strong></span><span>Tiempo medio de cierre <strong>{sales?.totals?.average_close_days == null ? "—" : `${sales.totals.average_close_days} días`}</strong></span></div></section>
    <section className="admin-panel"><h3>Información para decisiones</h3><div className="inventory-line"><span>Leads pendientes de atención <strong>{decisions?.pending_leads || 0}</strong></span><span>Propiedades no publicadas modificadas <strong>{decisions?.recent_unpublished || 0}</strong></span></div><AdminTable heads={["Propiedad", "Visualizaciones", "Consultas"]}>{(decisions?.high_views_low_inquiries || []).map((x: any) => <tr key={x.id}><td>{x.title}</td><td>{x.views}</td><td>{x.inquiries_count}</td></tr>)}</AdminTable></section>
  </AdminLayout>;
}

function ListingPerformance({ days }: { days: number }) {
  const [rows, setRows] = useState<Array<any>>([]);
  useEffect(() => { apiFetch<Array<any>>(`/api/v1/admin/bi/listings/?days=${days}`).then(setRows).catch(() => setRows([])); }, [days]);
  return <section className="admin-panel bi-table"><h3>Resultados por propiedad</h3><p className="muted">Adiciones a favoritos son acciones registradas, no el total actual guardado en navegadores.</p><AdminTable heads={["Propiedad", "Visualizaciones", "Adiciones a favoritos", "Consultas", "Programadas", "Realizadas", "Ventas", "Vista → consulta", "Consulta → realizada", "Realizada → venta"]}>{rows.map((x) => <tr key={x.id}><td>{x.title}</td><td>{x.views}</td><td>{x.favorite_additions}</td><td>{x.inquiries_count}</td><td>{x.visits_scheduled}</td><td>{x.visits_completed}</td><td>{x.sales_count}</td><td>{x.view_to_inquiry_rate == null ? "—" : `${Math.round(x.view_to_inquiry_rate)}%`}</td><td>{x.inquiry_to_visit_rate == null ? "—" : `${Math.round(x.inquiry_to_visit_rate)}%`}</td><td>{x.visit_to_sale_rate == null ? "—" : `${Math.round(x.visit_to_sale_rate)}%`}</td></tr>)}</AdminTable></section>;
}

const resources: Record<string, { title: string; endpoint: string; exportable?: boolean; heads: string[]; row: (x: any) => React.ReactNode[] }> = {
  clientes: { title: "Clientes", endpoint: "leads", exportable: true, heads: ["Nombre", "Correo", "Teléfono", "Etapa", "Actualizado"], row: (x) => [x.name, x.email || "—", x.phone_raw || "—", x.status_label, formatDate(x.updated_at)] },
  consultas: { title: "Consultas", endpoint: "inquiries", exportable: true, heads: ["Cliente", "Propiedad", "Canal", "Estado", "Recibida"], row: (x) => [x.lead_name, x.listing_title || "Consulta general", x.channel, x.status_label, formatDate(x.created_at)] },
  visitas: { title: "Visitas", endpoint: "visits", heads: ["Cliente", "Programada", "Estado", "Responsable"], row: (x) => [x.lead_name, formatDate(x.scheduled_at), x.status, x.assigned_to || "—"] },
  ventas: { title: "Ventas", endpoint: "sales", exportable: true, heads: ["Cliente", "Precio de venta", "Comisión", "Cierre"], row: (x) => [x.lead_name, formatCurrency(Number(x.sale_price)), x.commission_amount ? formatCurrency(Number(x.commission_amount)) : "—", formatDate(x.closed_at)] },
};

export function AdminResourcePage({ resource }: { resource: keyof typeof resources }) {
  const config = resources[resource];
  const [rows, setRows] = useState<Array<any>>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState<any>(); const [timeline, setTimeline] = useState<any>(); const [leads, setLeads] = useState<any[]>([]); const [properties, setProperties] = useState<any[]>([]);
  const load = useCallback(() => fetchAllPages<any>(`/api/v1/admin/${config.endpoint}/?page_size=100&search=${encodeURIComponent(query)}`).then(setRows), [config.endpoint, query]);
  useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]);
  useEffect(() => { if (resource === "visitas" || resource === "ventas") Promise.all([fetchAllPages<any>("/api/v1/admin/leads/?page_size=100"), fetchAllPages<any>("/api/v1/admin/properties/?page_size=100")]).then(([a, b]) => { setLeads(a); setProperties(b); }).catch(() => undefined); }, [resource]);
  const begin = (row?: any) => { setEditing(row ? { ...row } : resource === "visitas" ? { lead: "", offering: "", scheduled_at: "", status: "SCHEDULED", notes: "" } : resource === "ventas" ? { lead: "", offering: "", listing: "", sale_price: "", commission_rate: "", closed_at: "", status: "CLOSED" } : undefined); setTimeline(undefined); if (row && resource === "clientes") apiFetch(`/api/v1/admin/leads/${row.id}/timeline/`).then(setTimeline).catch(() => undefined); };
  const save = async () => {
    if (!editing) return; setBusy(true); setError("");
    try {
      const exists = rows.some((row) => row.id === editing.id);
      const payload = resource === "clientes" ? { status: editing.status, owner_user: editing.owner_user || null, version: editing.version }
        : resource === "consultas" ? { status: editing.status, assigned_to: editing.assigned_to || null }
        : resource === "visitas" ? { lead: editing.lead, offering: editing.offering, scheduled_at: new Date(editing.scheduled_at).toISOString(), status: editing.status, assigned_to: editing.assigned_to || null, notes: editing.notes || null }
        : exists ? { status: editing.status } : { lead: editing.lead, offering: editing.offering, listing: editing.listing || null, sale_price: editing.sale_price, commission_rate: editing.commission_rate || null, closed_at: new Date(editing.closed_at).toISOString(), status: editing.status };
      await apiFetch(exists ? `/api/v1/admin/${config.endpoint}/${editing.id}/` : `/api/v1/admin/${config.endpoint}/`, { method: exists ? "PATCH" : "POST", body: JSON.stringify(payload) });
      setEditing(undefined); await load();
    } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar"); } finally { setBusy(false); }
  };
  const propertyOptions = properties.map((row) => ({ listing: row.id, offering: row.offering, title: row.title }));
  return <AdminLayout title={config.title}><div className="admin-title"><div><span className="eyebrow">Operación</span><h2>{config.title}</h2></div>{(resource === "visitas" || resource === "ventas") && <button className="button" onClick={() => begin()}>{resource === "visitas" ? "Nueva visita" : "Registrar venta"}</button>}</div>
    <div className="admin-toolbar"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={`Buscar en ${config.title.toLowerCase()}`} /><span>{rows.length} registros</span>{config.exportable && <a className="button secondary" href={`/api/v1/admin/${config.endpoint}/export/`}>Exportar CSV</a>}</div>
    {editing && <section className="admin-panel"><h3>{editing.id ? "Detalle y seguimiento" : resource === "visitas" ? "Nueva visita" : "Registrar venta"}</h3><div className="admin-form-grid">
      {(resource === "visitas" || resource === "ventas") && !editing.id && <><label className="field"><span>Cliente</span><select value={editing.lead} onChange={(e) => setEditing({ ...editing, lead: e.target.value })}><option value="">Selecciona</option>{leads.map((lead) => <option value={lead.id} key={lead.id}>{lead.name}</option>)}</select></label><label className="field"><span>Propiedad</span><select value={editing.offering} onChange={(e) => { const selected = propertyOptions.find((p) => p.offering === e.target.value); setEditing({ ...editing, offering: e.target.value, listing: selected?.listing || "" }); }}><option value="">Selecciona</option>{propertyOptions.map((property) => <option value={property.offering} key={property.offering}>{property.title}</option>)}</select></label></>}
      {resource === "clientes" && <label className="field"><span>Etapa</span><select value={editing.status} onChange={(e) => setEditing({ ...editing, status: e.target.value })}>{[["Nuevo","NEW"],["Contactado","CONTACTED"],["Interesado","INTERESTED"],["Visita programada","VISIT_SCHEDULED"],["Negociación","NEGOTIATING"],["Ganado","WON"],["Perdido","LOST"]].map(([label,value]) => <option value={value} key={value}>{label}</option>)}</select></label>}
      {resource === "consultas" && <><label className="field"><span>Estado</span><select value={editing.status} onChange={(e) => setEditing({ ...editing, status: e.target.value })}>{[["Nueva","NEW"],["Vista","VIEWED"],["Atendida","ATTENDED"]].map(([label,value]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Intención</span><input value={editing.intent_label || ""} readOnly /></label><label className="field full"><span>Mensaje</span><textarea value={editing.message || ""} readOnly /></label></>}
      {resource === "visitas" && <><label className="field"><span>Fecha y hora</span><input type="datetime-local" value={editing.scheduled_at?.slice(0,16) || ""} onChange={(e) => setEditing({ ...editing, scheduled_at: e.target.value })} /></label><label className="field"><span>Estado</span><select value={editing.status} onChange={(e) => setEditing({ ...editing, status: e.target.value })}>{[["Programada","SCHEDULED"],["Realizada","COMPLETED"],["Cancelada","CANCELLED"],["No asistó","NO_SHOW"]].map(([label,value]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="field full"><span>Notas</span><textarea value={editing.notes || ""} onChange={(e) => setEditing({ ...editing, notes: e.target.value })} /></label></>}
      {resource === "ventas" && <><label className="field"><span>Precio de venta</span><input type="number" min="0" step="0.01" value={editing.sale_price} disabled={Boolean(editing.id)} onChange={(e) => setEditing({ ...editing, sale_price: e.target.value })} /></label><label className="field"><span>Comisión %</span><input type="number" min="0" max="100" step="0.01" value={editing.commission_rate || ""} disabled={Boolean(editing.id)} onChange={(e) => setEditing({ ...editing, commission_rate: e.target.value })} /></label><label className="field"><span>Fecha de cierre</span><input type="datetime-local" value={editing.closed_at?.slice(0,16) || ""} disabled={Boolean(editing.id)} onChange={(e) => setEditing({ ...editing, closed_at: e.target.value })} /></label><label className="field"><span>Estado</span><select value={editing.status} onChange={(e) => setEditing({ ...editing, status: e.target.value })}><option value="CLOSED">Cerrada</option><option value="CANCELLED">Cancelada</option></select></label></>}
    </div>{resource === "clientes" && timeline && <div className="crm-timeline"><div className="inventory-line"><span>Origen <strong>{timeline.attribution.source || "Directo"}</strong></span><span>Campaña <strong>{timeline.attribution.campaign || "—"}</strong></span><span>Medio <strong>{timeline.attribution.medium || "—"}</strong></span></div>{timeline.events.map((event: any, index: number) => <div key={`${event.kind}-${index}`}><i /><span><strong>{event.label}</strong><small>{formatDate(event.at)}{event.detail ? ` · ${event.detail}` : ""}</small></span></div>)}</div>}<div className="admin-form-actions"><button className="button secondary" onClick={() => setEditing(undefined)}>Cerrar</button><button className="button" disabled={busy} onClick={() => void save()}>{busy ? "Guardando…" : "Guardar cambios"}</button></div></section>}
    {error ? <p className="form-error">{error}</p> : rows.length ? <AdminTable heads={[...config.heads, "Acciones"]}>{rows.map((x) => <tr key={x.id}>{config.row(x).map((value, index) => <td key={index}>{value}</td>)}<td><button className="text-link" onClick={() => begin(x)}>Abrir</button></td></tr>)}</AdminTable> : <div className="empty-state"><p>No hay {config.title.toLowerCase()} en este momento.</p></div>}
  </AdminLayout>;
}

export function AdminAuditPage() {
  const [rows, setRows] = useState<any[]>([]); const [filters, setFilters] = useState({ actor_user: "", action: "", entity_type: "", success: "", search: "" }); const [selected, setSelected] = useState<any>();
  useEffect(() => { const query = new URLSearchParams(Object.entries(filters).filter(([,value]) => value)); fetchAllPages<any>(`/api/v1/admin/audit/?page_size=100&${query}`).then(setRows); }, [filters]);
  const names: Record<string,string> = { amount_min: "Precio", amount_max: "Precio máximo", status: "Estado", is_published: "Publicación", commission_amount: "Comisión", sale_price: "Precio de venta", role_name: "Rol" };
  const changes = selected ? Array.from(new Set([...Object.keys(selected.old_values || {}), ...Object.keys(selected.new_values || {})])) : [];
  const show = (key: string, value: unknown) => value == null ? "—" : key.includes("price") || key.includes("amount") ? formatCurrency(Number(value)) : typeof value === "boolean" ? value ? "Sí" : "No" : String(value);
  return <AdminLayout title="Historial"><div className="admin-title"><div><span className="eyebrow">Historial</span><h2>Actividad del negocio</h2></div></div><div className="admin-toolbar"><input placeholder="Buscar" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /><input placeholder="ID de usuario" value={filters.actor_user} onChange={(e) => setFilters({ ...filters, actor_user: e.target.value })} /><select value={filters.action} onChange={(e) => setFilters({ ...filters, action: e.target.value })}><option value="">Todas las acciones</option><option value="CREATE">Creación</option><option value="UPDATE">Cambio</option><option value="PUBLISH">Publicación</option><option value="ARCHIVE">Archivo</option><option value="PRICE_CHANGE">Cambio de precio</option></select><input placeholder="Tipo de registro" value={filters.entity_type} onChange={(e) => setFilters({ ...filters, entity_type: e.target.value })} /><select value={filters.success} onChange={(e) => setFilters({ ...filters, success: e.target.value })}><option value="">Cualquier resultado</option><option value="true">Realizada</option><option value="false">Fallida</option></select></div>{selected && <section className="admin-panel"><h3>Qué cambió</h3>{changes.length ? changes.map((key) => <div className="audit-change" key={key}><span>{names[key] || key.replaceAll("_", " ")}</span><strong>{show(key, selected.old_values?.[key])} → {show(key, selected.new_values?.[key])}</strong></div>) : <p className="muted">Este evento no contiene cambios de campos.</p>}{selected.reason && <p>Motivo: {selected.reason}</p>}</section>}<AdminTable heads={["Fecha", "Usuario", "Acción", "Registro", "Resultado"]}>{rows.map((x) => <tr key={x.id} onClick={() => setSelected(x)}><td>{formatDate(x.occurred_at)}</td><td>{x.actor_name || "Sistema"}</td><td>{x.action_label}</td><td>{x.entity_type}</td><td>{x.success ? "Realizada" : "Fallida"}</td></tr>)}</AdminTable></AdminLayout>;
}

export function AdminCatalogsPage() {
  const [types, setTypes] = useState<any[]>([]); const [amenities, setAmenities] = useState<any[]>([]); const [features, setFeatures] = useState<any[]>([]);
  const load = useCallback(() => Promise.all(["property-types", "amenities", "features"].map((x) => fetchAllPages<any>(`/api/v1/admin/${x}/?page_size=100`))).then(([a,b,c]) => {setTypes(a); setAmenities(b); setFeatures(c);}), []);
  useEffect(() => { void load(); }, [load]);
  return <AdminLayout title="Catálogos"><div className="admin-title"><div><span className="eyebrow">Configuración de negocio</span><h2>Catálogos</h2></div></div><div className="admin-panels"><CatalogBlock title="Tipos de propiedad" endpoint="property-types" rows={types} onChanged={load} /><CatalogBlock title="Amenidades" endpoint="amenities" rows={amenities} onChanged={load} /></div><FeatureCatalog rows={features} onChanged={load} /><GeoCatalogManager /></AdminLayout>;
}

function FeatureCatalog({ rows, onChanged }: { rows: any[]; onChanged: () => Promise<void> }) {
  const empty = { label: "", code: "", category: "General", data_type: "BOOLEAN", unit: "", is_public: true, is_filterable: false, is_active: true, choices: [] as any[] }; const [form, setForm] = useState<any>(); const [error, setError] = useState("");
  const save = async () => { try { await apiFetch(form.id ? `/api/v1/admin/features/${form.id}/` : "/api/v1/admin/features/", { method: form.id ? "PATCH" : "POST", body: JSON.stringify({ ...form, code: form.code || slugify(form.label), unit: form.unit || null, choices_input: form.data_type === "CHOICE" ? form.choices.map((choice: any, index: number) => ({ value: choice.value || slugify(choice.label), label: choice.label, sort_order: index })) : [] }) }); setForm(undefined); await onChanged(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar la característica"); } };
  return <section className="admin-panel"><div className="admin-title"><h3>Características</h3><button className="button secondary" onClick={() => setForm({ ...empty })}>Nueva característica</button></div>{error && <p className="form-error">{error}</p>}{form && <div><div className="admin-form-grid"><label className="field"><span>Nombre</span><input value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} /></label><label className="field"><span>Categoría</span><input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label className="field"><span>Tipo</span><select value={form.data_type} onChange={(e) => setForm({ ...form, data_type: e.target.value })}><option value="BOOLEAN">Sí / No</option><option value="NUMBER">Número</option><option value="TEXT">Texto</option><option value="CHOICE">Opciones</option></select></label><label className="field"><span>Unidad</span><input value={form.unit || ""} onChange={(e) => setForm({ ...form, unit: e.target.value })} /></label></div><div className="filter-checks"><label className="check-chip"><input type="checkbox" checked={form.is_public} onChange={(e) => setForm({ ...form, is_public: e.target.checked })} /><span>Pública</span></label><label className="check-chip"><input type="checkbox" checked={form.is_filterable} onChange={(e) => setForm({ ...form, is_filterable: e.target.checked })} /><span>Disponible como filtro</span></label></div>{form.data_type === "CHOICE" && <div><h4>Opciones</h4>{form.choices.map((choice: any, index: number) => <div className="admin-list-row" key={choice.id || index}><input value={choice.label} placeholder="Etiqueta" onChange={(e) => setForm({ ...form, choices: form.choices.map((item: any, i: number) => i === index ? { ...item, label: e.target.value } : item) })} /><button onClick={() => setForm({ ...form, choices: form.choices.filter((_: any, i: number) => i !== index) })}>Quitar</button></div>)}<button className="button secondary" onClick={() => setForm({ ...form, choices: [...form.choices, { label: "", value: "" }] })}>Añadir opción</button></div>}<div className="admin-form-actions"><button className="button secondary" onClick={() => setForm(undefined)}>Cancelar</button><button className="button" onClick={() => void save()}>Guardar</button></div></div>}{rows.map((row) => <div className="admin-list-row" key={row.id}><span>{row.label}<small>{row.category} · {row.data_type}{row.unit ? ` · ${row.unit}` : ""}</small></span><span>{row.is_public ? "Pública" : "Interna"} · {row.is_filterable ? "Filtrable" : "No filtrable"}</span><button onClick={() => setForm({ ...row, choices: row.choices || [] })}>Configurar</button></div>)}</section>;
}

function GeoCatalogManager() {
  const [states, setStates] = useState<any[]>([]); const [municipalities, setMunicipalities] = useState<any[]>([]); const [localities, setLocalities] = useState<any[]>([]); const [neighborhoods, setNeighborhoods] = useState<any[]>([]); const [kind, setKind] = useState("states"); const [form, setForm] = useState<any>({ name: "", parent: "", locality: "", code: "" }); const [editing, setEditing] = useState<any>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(() => Promise.all(["states","municipalities","localities","neighborhoods"].map((endpoint) => fetchAllPages<any>(`/api/v1/admin/${endpoint}/?page_size=100`))).then(([a,b,c,d]) => { setStates(a); setMunicipalities(b); setLocalities(c); setNeighborhoods(d); }), []);
  useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]);
  const collections: Record<string, any[]> = { states, municipalities, localities, neighborhoods };
  const labels: Record<string, string> = { states: "Estados", municipalities: "Municipios", localities: "Localidades", neighborhoods: "Colonias" };
  const reset = () => { setEditing(undefined); setForm({ name: "", parent: "", locality: "", code: "" }); };
  const save = async () => { setError(""); setBusy(true); try { const payload = kind === "states" ? { name: form.name, code: form.code, is_active: editing?.is_active ?? true } : kind === "municipalities" ? { name: form.name, state: form.parent, is_active: editing?.is_active ?? true } : kind === "localities" ? { name: form.name, municipality: form.parent, is_active: editing?.is_active ?? true } : { name: form.name, municipality: form.parent, locality: form.locality || null, postal_code: form.code || "", is_active: editing?.is_active ?? true }; await apiFetch(editing ? `/api/v1/admin/${kind}/${editing.id}/` : `/api/v1/admin/${kind}/`, { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); reset(); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar la ubicación"); } finally { setBusy(false); } };
  const beginEdit = (item: any) => { setEditing(item); setForm({ name: item.name, parent: kind === "municipalities" ? item.state : item.municipality || "", locality: item.locality || "", code: kind === "states" ? item.code : item.postal_code || "" }); };
  const toggle = async (item: any) => { setBusy(true); setError(""); try { await apiFetch(`/api/v1/admin/${kind}/${item.id}/`, { method: item.is_active ? "DELETE" : "PATCH", body: item.is_active ? undefined : JSON.stringify({ is_active: true }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible cambiar el estado"); } finally { setBusy(false); } };
  const hardDelete = async (item: any) => { setError(""); try { const preview = await apiFetch<any>(`/api/v1/admin/${kind}/${item.id}/delete-preview/`); if (!preview.can_delete) return setError("Esta ubicación está en uso y sólo puede mantenerse inactiva."); const confirmation = window.prompt(`Para eliminar definitivamente, escribe: ${item.name}`); if (confirmation !== item.name) return; const reason = window.prompt("Motivo de la eliminación (mínimo 10 caracteres)"); if (!reason) return; await apiFetch(`/api/v1/admin/${kind}/${item.id}/hard-delete/`, { method: "POST", body: JSON.stringify({ confirmation, reason }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible eliminar definitivamente"); } };
  const parents = kind === "municipalities" ? states : municipalities;
  return <section className="admin-panel"><h3>Ubicaciones auxiliares</h3><div className="admin-toolbar"><select value={kind} onChange={(e) => { setKind(e.target.value); reset(); }}>{Object.entries(labels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select><input aria-label="Nombre de ubicación" placeholder="Nombre" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />{kind !== "states" && <select aria-label={kind === "municipalities" ? "Estado" : "Municipio"} value={form.parent} onChange={(e) => setForm({ ...form, parent: e.target.value, locality: "" })}><option value="">{kind === "municipalities" ? "Estado" : "Municipio"}</option>{parents.filter((item) => item.is_active || item.id === form.parent).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select>}{kind === "neighborhoods" && <select aria-label="Localidad" value={form.locality} onChange={(e) => setForm({ ...form, locality: e.target.value })}><option value="">Sin localidad</option>{localities.filter((item) => item.municipality === form.parent && (item.is_active || item.id === form.locality)).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select>}{(kind === "states" || kind === "neighborhoods") && <input placeholder={kind === "states" ? "Código" : "Código postal"} value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} />}<button className="button" disabled={busy || !form.name || (kind !== "states" && !form.parent) || (kind === "states" && !form.code)} onClick={() => void save()}>{editing ? "Guardar" : "Añadir"}</button>{editing && <button className="button secondary" onClick={reset}>Cancelar</button>}</div>{error && <p className="form-error">{error}</p>}<div>{collections[kind].map((item) => <div className="admin-list-row" key={item.id}><span>{item.name}</span><small>{item.is_active ? "Activa" : "Inactiva"}</small><div className="table-actions"><button disabled={busy} onClick={() => beginEdit(item)}>Editar</button><button disabled={busy} onClick={() => void toggle(item)}>{item.is_active ? "Desactivar" : "Reactivar"}</button>{!item.is_active && <button disabled={busy} onClick={() => void hardDelete(item)}>Eliminar definitivamente</button>}</div></div>)}</div></section>;
}
function CatalogBlock({ title, endpoint, rows, onChanged }: { title: string; endpoint: string; rows: any[]; onChanged: () => Promise<void> }) {
  const [name, setName] = useState(""); const [editing, setEditing] = useState<any>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const payload = (value: string, current?: any) => endpoint === "property-types"
    ? { code: current?.code || slugify(value), name: value, is_active: current?.is_active ?? true, sort_order: current?.sort_order || 0 }
    : endpoint === "amenities"
      ? { name: value, slug: current?.slug || slugify(value), category: current?.category || "DEVELOPMENT", is_active: current?.is_active ?? true, sort_order: current?.sort_order || 0 }
      : { code: current?.code || slugify(value), label: value, category: current?.category || "General", data_type: current?.data_type || "TEXT", is_public: current?.is_public ?? true, is_filterable: current?.is_filterable ?? false, is_active: current?.is_active ?? true, sort_order: current?.sort_order || 0 };
  const save = async () => { if (!name.trim()) return; setBusy(true); setError(""); try { await apiFetch(editing ? `/api/v1/admin/${endpoint}/${editing.id}/` : `/api/v1/admin/${endpoint}/`, { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload(name.trim(), editing)) }); setName(""); setEditing(undefined); await onChanged(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar"); } finally { setBusy(false); } };
  const toggle = async (row: any) => { setBusy(true); try { await apiFetch(`/api/v1/admin/${endpoint}/${row.id}/`, { method: "PATCH", body: JSON.stringify({ is_active: !row.is_active }) }); await onChanged(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible actualizar"); } finally { setBusy(false); } };
  return <section className="admin-panel"><h3>{title}</h3><div className="admin-toolbar"><input value={name} onChange={(e) => setName(e.target.value)} placeholder={editing ? "Nuevo nombre" : "Nueva opción"} /><button className="button" disabled={busy || !name.trim()} onClick={() => void save()}>{busy ? "Guardando…" : editing ? "Guardar" : "Añadir"}</button>{editing && <button className="button secondary" onClick={() => { setEditing(undefined); setName(""); }}>Cancelar</button>}</div>{error && <p className="form-error">{error}</p>}{rows.length ? rows.map((x) => <div className="admin-list-row" key={x.id}><span>{x.name || x.label}</span><small>{x.is_active ? "Activa" : "Inactiva"}</small><div className="table-actions"><button onClick={() => { setEditing(x); setName(x.name || x.label); }}>Renombrar</button><button onClick={() => void toggle(x)}>{x.is_active ? "Desactivar" : "Reactivar"}</button></div></div>) : <p className="muted">No hay opciones.</p>}</section>;
}

const simpleResources: Record<string, { title: string; endpoint: string; heads: string[]; cells: (x: any) => React.ReactNode[] }> = {
  desarrolladoras: { title: "Desarrolladoras", endpoint: "developers", heads: ["Nombre", "Razón social", "Sitio", "Estado"], cells: (x) => [x.name, x.legal_name || "—", x.website || "—", x.is_active ? "Activa" : "Inactiva"] },
  modelos: { title: "Modelos", endpoint: "models", heads: ["Modelo", "Desarrolladora", "Presente en", "Estado"], cells: (x) => [x.name, x.developer_name, x.developments?.map((d: any) => d.name).join(", ") || "Sin desarrollo", x.is_active ? "Activo" : "Inactivo"] },
  publicaciones: { title: "Publicaciones", endpoint: "listings", heads: ["Propiedad", "Publicación", "Destacada", "Actualizada"], cells: (x) => [x.title, x.is_published ? "Publicada" : "Sin publicar", x.is_featured ? "Sí" : "No", formatDate(x.updated_at)] },
  marketing: { title: "Marketing", endpoint: "marketing-campaigns", heads: ["Campaña", "Canal", "Clave de campaña", "Estado"], cells: (x) => [x.name, x.channel, x.utm_campaign, x.is_active ? "Activa" : "Finalizada"] },
  usuarios: { title: "Usuarios", endpoint: "users", heads: ["Nombre", "Correo", "Rol", "Activo", "MFA"], cells: (x) => [x.name, x.email, x.role, x.is_active ? "Sí" : "No", x.mfa_enabled ? "Configurado" : "Pendiente"] },
};

export function AdminSimpleResourcePage({ resource }: { resource: keyof typeof simpleResources }) {
  if (resource === "desarrolladoras" || resource === "modelos") return <EditableCatalogEntityPage resource={resource} />;
  if (resource === "usuarios") return <UserManagementPage />;
  if (resource === "marketing") return <MarketingManagementPage />;
  return <ReadonlySimpleResourcePage resource={resource} />;
}

function MarketingManagementPage() {
  const [campaigns, setCampaigns] = useState<any[]>([]); const [spend, setSpend] = useState<any[]>([]); const [editing, setEditing] = useState<any>(); const [spendForm, setSpendForm] = useState<any>(); const [selected, setSelected] = useState<any>(); const [results, setResults] = useState<any>(); const [utmContent, setUtmContent] = useState(""); const [destination, setDestination] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(() => Promise.all([fetchAllPages<any>("/api/v1/admin/marketing-campaigns/?page_size=100&archived=all"), fetchAllPages<any>("/api/v1/admin/marketing-spend/?page_size=100")]).then(([a, b]) => { setCampaigns(a); setSpend(b); }), []);
  useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]);
  const saveCampaign = async () => { setBusy(true); setError(""); try { const exists = campaigns.some((item) => item.id === editing.id); await apiFetch(exists ? `/api/v1/admin/marketing-campaigns/${editing.id}/` : "/api/v1/admin/marketing-campaigns/", { method: exists ? "PATCH" : "POST", body: JSON.stringify({ name: editing.name, utm_campaign: editing.utm_campaign, channel: editing.channel, planned_budget: editing.planned_budget || 0, utm_source: editing.utm_source, utm_medium: editing.utm_medium, default_landing_path: editing.default_landing_path || "/", start_date: editing.start_date, end_date: editing.end_date || null, is_active: editing.is_active ?? true, notes: editing.notes || null, ...(exists ? { version: editing.version } : {}) }) }); setEditing(undefined); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar la campaña"); } finally { setBusy(false); } };
  const saveSpend = async () => { setBusy(true); setError(""); try { const exists = spend.some((item) => item.id === spendForm.id); await apiFetch(exists ? `/api/v1/admin/marketing-spend/${spendForm.id}/` : "/api/v1/admin/marketing-spend/", { method: exists ? "PATCH" : "POST", body: JSON.stringify({ campaign: spendForm.campaign, date: spendForm.date, amount: spendForm.amount, currency: "MXN" }) }); setSpendForm(undefined); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar el gasto"); } finally { setBusy(false); } };
  const voidSpend = async (item: any) => { const reason = window.prompt("Motivo de anulación"); if (!reason) return; setBusy(true); try { await apiFetch(`/api/v1/admin/marketing-spend/${item.id}/void/`, { method: "POST", body: JSON.stringify({ reason }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible anular el gasto"); } finally { setBusy(false); } };
  const archive = async (item: any) => { setBusy(true); try { await apiFetch(`/api/v1/admin/marketing-campaigns/${item.id}/`, { method: "DELETE" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible archivar la campaña"); } finally { setBusy(false); } };
  const restore = async (item: any) => { setBusy(true); try { await apiFetch(`/api/v1/admin/marketing-campaigns/${item.id}/restore/`, { method: "POST", body: "{}" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible restaurar la campaña"); } finally { setBusy(false); } };
  const open = async (campaign: any) => { setSelected(campaign); setDestination(campaign.default_landing_path || "/"); setResults(await apiFetch(`/api/v1/admin/marketing-campaigns/${campaign.id}/results/`)); };
  const channel = (value: string) => { const defaults: Record<string, [string,string]> = { INSTAGRAM: ["instagram","paid_social"], FACEBOOK: ["facebook","paid_social"], TIKTOK: ["tiktok","paid_social"], GOOGLE: ["google","paid_search"], OTHER: ["other","paid"] }; const [utm_source, utm_medium] = defaults[value]; setEditing({ ...editing, channel: value, utm_source, utm_medium }); };
  const generatedUrl = selected && results ? `${results.public_site_url}${destination.startsWith("/") ? destination : `/${destination}`}?${new URLSearchParams({ utm_source: selected.utm_source, utm_medium: selected.utm_medium, utm_campaign: selected.utm_campaign, ...(utmContent ? { utm_content: utmContent } : {}) }).toString()}` : "";
  const metric = (label: string, value: unknown, money=false, suffix="") => <span><small>{label}</small><strong>{value == null ? "—" : money ? formatCurrency(Number(value)) : `${value}${suffix}`}</strong></span>;
  return <AdminLayout title="Marketing"><div className="admin-title"><div><span className="eyebrow">Audiencia y resultados</span><h2>Marketing</h2></div><div className="table-actions"><button className="button secondary" onClick={() => setSpendForm({ campaign: campaigns[0]?.id || "", date: new Date().toISOString().slice(0,10), amount: "" })}>Registrar gasto real</button><button className="button" onClick={() => setEditing({ name: "", utm_campaign: "", channel: "INSTAGRAM", planned_budget: "", utm_source: "instagram", utm_medium: "paid_social", default_landing_path: "/", start_date: new Date().toISOString().slice(0,10), is_active: true, notes: "" })}>Nueva campaña</button></div></div>
    <div className="marketing-flow" aria-label="Pipeline de marketing">{["Crear campaña","Generar link UTM","Publicar enlace","Registrar gasto","Tráfico automático","Consulta","Cliente","Visita","Venta","Resultados"].map((step, index) => <span key={step}>{step}{index < 9 && <b>↓</b>}</span>)}</div>
    {error && <p className="form-error">{error}</p>}
    {editing && <section className="admin-panel"><h3>{editing.id ? "Editar campaña" : "Nueva campaña"}</h3><div className="admin-form-grid"><label className="field"><span>Nombre</span><input value={editing.name || ""} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></label><label className="field"><span>UTM campaign</span><input value={editing.utm_campaign || ""} onChange={(e) => setEditing({ ...editing, utm_campaign: slugify(e.target.value) })} /></label><label className="field"><span>Canal</span><select value={editing.channel} onChange={(e) => channel(e.target.value)}>{[["Instagram","INSTAGRAM"],["Facebook","FACEBOOK"],["TikTok","TIKTOK"],["Google","GOOGLE"],["Otro","OTHER"]].map(([label,value]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Presupuesto planeado</span><input type="number" min="0" value={editing.planned_budget || ""} onChange={(e) => setEditing({ ...editing, planned_budget: e.target.value })} /></label><label className="field"><span>UTM source</span><input value={editing.utm_source || ""} onChange={(e) => setEditing({ ...editing, utm_source: e.target.value })} /></label><label className="field"><span>UTM medium</span><input value={editing.utm_medium || ""} onChange={(e) => setEditing({ ...editing, utm_medium: e.target.value })} /></label><label className="field"><span>Ruta de destino predeterminada</span><input value={editing.default_landing_path || "/"} onChange={(e) => setEditing({ ...editing, default_landing_path: e.target.value })} /></label><label className="field"><span>Inicio</span><input type="date" value={editing.start_date || ""} onChange={(e) => setEditing({ ...editing, start_date: e.target.value })} /></label><label className="field"><span>Fin</span><input type="date" value={editing.end_date || ""} onChange={(e) => setEditing({ ...editing, end_date: e.target.value })} /></label><label className="field full"><span>Notas</span><textarea value={editing.notes || ""} onChange={(e) => setEditing({ ...editing, notes: e.target.value })} /></label></div><div className="admin-form-actions"><button className="button secondary" onClick={() => setEditing(undefined)}>Cancelar</button><button className="button" disabled={busy} onClick={() => void saveCampaign()}>{busy ? "Guardando…" : "Guardar"}</button></div></section>}
    {spendForm && <section className="admin-panel"><h3>Gasto de campaña</h3><div className="admin-form-grid"><label className="field"><span>Campaña</span><select value={spendForm.campaign} onChange={(e) => setSpendForm({ ...spendForm, campaign: e.target.value })}>{campaigns.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Fecha</span><input type="date" value={spendForm.date} onChange={(e) => setSpendForm({ ...spendForm, date: e.target.value })} /></label><label className="field"><span>Importe MXN</span><input type="number" min="0" step="0.01" value={spendForm.amount} onChange={(e) => setSpendForm({ ...spendForm, amount: e.target.value })} /></label></div><div className="admin-form-actions"><button className="button secondary" onClick={() => setSpendForm(undefined)}>Cancelar</button><button className="button" disabled={busy} onClick={() => void saveSpend()}>{busy ? "Guardando…" : "Guardar gasto"}</button></div></section>}
    <section className="admin-panel"><h3>Campañas</h3><AdminTable heads={["Campaña","Canal","Presupuesto","Gastado","Ejecución","Acciones"]}>{campaigns.map((item) => <tr key={item.id}><td><button className="text-link" onClick={() => void open(item)}>{item.name}</button><small>{item.utm_campaign}</small></td><td>{item.channel_label}</td><td>{formatCurrency(Number(item.planned_budget))}</td><td>{formatCurrency(Number(item.actual_spend))}</td><td>{item.execution_percent == null ? "—" : `${item.execution_percent}%`}</td><td><div className="table-actions"><button disabled={Boolean(item.archived_at)} onClick={() => setEditing(item)}>Editar</button><button disabled={busy} onClick={() => void (item.archived_at ? restore(item) : archive(item))}>{item.archived_at ? "Restaurar" : "Archivar"}</button></div></td></tr>)}</AdminTable></section>
    {selected && results && <section className="admin-panel campaign-detail"><span className="eyebrow">Resultados de campaña</span><h3>{selected.name}</h3><div className="campaign-metrics">{metric("Presupuesto",results.planned_budget,true)}{metric("Gasto",results.spend,true)}{metric("Disponible",results.available_budget,true)}{metric("Ejecución",results.execution_percent,false,"%")} {metric("Sesiones",results.sessions)}{metric("Clientes adquiridos",results.acquired_clients)}{metric("Consultas",results.inquiries)}{metric("Visitas realizadas",results.completed_visits)}{metric("Ventas cerradas",results.closed_sales)}{metric("Valor de ventas atribuidas",results.attributed_sales_value,true)}{metric("Comisión atribuida",results.attributed_commission,true)}{metric("Costo por cliente",results.cost_per_client,true)}{metric("Costo por consulta",results.cost_per_inquiry,true)}{metric("Costo por visita",results.cost_per_visit,true)}{metric("Costo por venta",results.cost_per_sale,true)}{metric("Contribución después de publicidad",results.contribution_after_advertising,true)}{metric("Retorno sobre gasto publicitario",results.return_on_ad_spend == null ? null : Number(results.return_on_ad_spend).toFixed(2),false,"×")}</div><div className="utm-generator"><h3>Generar enlace</h3><div className="admin-form-grid"><label className="field"><span>Destino</span><input value={destination} onChange={(e) => setDestination(e.target.value)} placeholder="/desarrollos/..." /></label><label className="field"><span>Contenido</span><input value={utmContent} onChange={(e) => setUtmContent(e.target.value)} placeholder="reel_01" /></label></div><code>{generatedUrl}</code><button className="button secondary" onClick={() => void navigator.clipboard.writeText(generatedUrl)}>Copiar enlace</button></div></section>}
    <section className="admin-panel"><h3>Histórico de gasto real</h3><p className="muted">Las ventas y comisiones se incorporan automáticamente desde CRM; aquí sólo se captura el gasto efectivamente pagado.</p><AdminTable heads={["Campaña","Fecha","Importe","Estado","Acciones"]}>{spend.map((item) => <tr key={item.id}><td>{item.campaign_name}</td><td>{item.date}</td><td>{formatCurrency(Number(item.amount))}</td><td>{item.is_voided ? "Anulado" : "Vigente"}</td><td><div className="table-actions"><button disabled={item.is_voided} onClick={() => setSpendForm(item)}>Editar</button><button disabled={busy || item.is_voided} onClick={() => void voidSpend(item)}>Anular</button></div></td></tr>)}</AdminTable></section>
  </AdminLayout>;
}

function ReadonlySimpleResourcePage({ resource }: { resource: Exclude<keyof typeof simpleResources, "desarrolladoras" | "modelos" | "usuarios"> }) {
  const config = simpleResources[resource]; const [rows, setRows] = useState<any[]>([]); const [error, setError] = useState("");
  useEffect(() => { fetchAllPages<any>(`/api/v1/admin/${config.endpoint}/?page_size=100`).then(setRows).catch((e) => setError(e.message)); }, [config.endpoint]);
  return <AdminLayout title={config.title}><div className="admin-title"><div><span className="eyebrow">Administración</span><h2>{config.title}</h2></div></div>{error ? <p className="form-error">{error}</p> : rows.length ? <AdminTable heads={config.heads}>{rows.map((x) => <tr key={x.id}>{config.cells(x).map((cell, i) => <td key={i}>{cell}</td>)}</tr>)}</AdminTable> : <div className="empty-state"><p>No hay registros.</p></div>}</AdminLayout>;
}

function EditableCatalogEntityPage({ resource }: { resource: "desarrolladoras" | "modelos" }) {
  const config = simpleResources[resource];
  const [rows, setRows] = useState<any[]>([]); const [developers, setDevelopers] = useState<any[]>([]); const [developments, setDevelopments] = useState<any[]>([]);
  const [editing, setEditing] = useState<any>(); const [name, setName] = useState(""); const [developerId, setDeveloperId] = useState(""); const [description, setDescription] = useState("");
  const [relation, setRelation] = useState<Record<string, string>>({}); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    const [items, developerData, developmentData] = await Promise.all([
      fetchAllPages<any>(`/api/v1/admin/${config.endpoint}/?page_size=100&archived=all`),
      fetchAllPages<any>("/api/v1/admin/developers/?page_size=100"),
      fetchAllPages<any>("/api/v1/admin/developments/?page_size=100"),
    ]);
    setRows(items); setDevelopers(developerData); setDevelopments(developmentData);
  }, [config.endpoint]);
  useEffect(() => {
    let active = true;
    Promise.all([
      fetchAllPages<any>(`/api/v1/admin/${config.endpoint}/?page_size=100&archived=all`),
      fetchAllPages<any>("/api/v1/admin/developers/?page_size=100"),
      fetchAllPages<any>("/api/v1/admin/developments/?page_size=100"),
    ]).then(([items, developerData, developmentData]) => {
      if (!active) return;
      setRows(items); setDevelopers(developerData); setDevelopments(developmentData);
    }).catch((e) => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [config.endpoint]);
  const begin = (row?: any) => { setEditing(row || {}); setName(row?.name || ""); setDeveloperId(row?.developer || ""); setDescription(row?.base_description || row?.legal_name || ""); setError(""); };
  const save = async () => {
    if (!name.trim() || (resource === "modelos" && !developerId)) return setError("Completa los campos obligatorios.");
    setBusy(true); setError("");
    try {
      const payload = resource === "modelos"
        ? { name: name.trim(), slug: editing?.slug || slugify(name), developer: developerId, base_description: description || null, is_active: true, ...(editing?.id ? { version: editing.version } : {}) }
        : { name: name.trim(), slug: editing?.slug || slugify(name), legal_name: description || null, is_active: true, ...(editing?.id ? { version: editing.version } : {}) };
      await apiFetch(editing?.id ? `/api/v1/admin/${config.endpoint}/${editing.id}/` : `/api/v1/admin/${config.endpoint}/`, { method: editing?.id ? "PATCH" : "POST", body: JSON.stringify(payload) });
      setEditing(undefined); setName(""); setDescription(""); setDeveloperId(""); await load();
    } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar"); } finally { setBusy(false); }
  };
  const archiveOrRestore = async (row: any) => { setBusy(true); try { await apiFetch(row.archived_at ? `/api/v1/admin/${config.endpoint}/${row.id}/restore/` : `/api/v1/admin/${config.endpoint}/${row.id}/`, { method: row.archived_at ? "POST" : "DELETE", body: row.archived_at ? "{}" : undefined }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible actualizar"); } finally { setBusy(false); } };
  const hardDelete = async (row: any) => { setError(""); try { const preview = await apiFetch<any>(`/api/v1/admin/${config.endpoint}/${row.id}/delete-preview/`); if (!preview.can_delete) return setError("Este registro tiene relaciones y sólo puede mantenerse archivado."); const confirmation = window.prompt(`Para eliminar definitivamente, escribe: ${row.name}`); if (confirmation !== row.name) return; const reason = window.prompt("Motivo de la eliminación (mínimo 10 caracteres)"); if (!reason) return; await apiFetch(`/api/v1/admin/${config.endpoint}/${row.id}/hard-delete/`, { method: "POST", body: JSON.stringify({ confirmation, reason }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible eliminar definitivamente"); } };
  const addRelation = async (model: any) => { const development = relation[model.id]; if (!development) return; setBusy(true); try { await apiFetch("/api/v1/admin/development-models/", { method: "POST", body: JSON.stringify({ development, housing_model: model.id, is_active: true }) }); setRelation((current) => ({ ...current, [model.id]: "" })); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible relacionar el modelo"); } finally { setBusy(false); } };
  const removeRelation = async (linkId: string) => { setBusy(true); try { await apiFetch(`/api/v1/admin/development-models/${linkId}/`, { method: "DELETE" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible desvincular"); } finally { setBusy(false); } };
  return <AdminLayout title={config.title}><div className="admin-title"><div><span className="eyebrow">Administración</span><h2>{config.title}</h2></div><button className="button" onClick={() => begin()}>Nuevo registro</button></div>
    {editing && <section className="admin-panel"><h3>{editing.id ? "Editar" : "Nuevo registro"}</h3><div className="admin-form-grid"><label className="field"><span>Nombre</span><input value={name} onChange={(e) => setName(e.target.value)} /></label>{resource === "modelos" && <label className="field"><span>Desarrolladora</span><select value={developerId} onChange={(e) => setDeveloperId(e.target.value)}><option value="">Selecciona</option>{developers.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}<label className="field"><span>{resource === "modelos" ? "Descripción base" : "Razón social"}</span><input value={description} onChange={(e) => setDescription(e.target.value)} /></label></div><div className="admin-form-actions"><button className="button secondary" onClick={() => setEditing(undefined)}>Cancelar</button><button className="button" disabled={busy} onClick={() => void save()}>{busy ? "Guardando…" : "Guardar"}</button></div></section>}
    {error && <p className="form-error">{error}</p>}
    {rows.length ? <AdminTable heads={[...config.heads, "Acciones"]}>{rows.map((row) => <tr key={row.id}>{config.cells(row).map((cell, i) => <td key={i}>{cell}</td>)}<td><div className="table-actions"><button disabled={Boolean(row.archived_at)} onClick={() => begin(row)}>Editar</button><button disabled={busy} onClick={() => void archiveOrRestore(row)}>{row.archived_at ? "Restaurar" : "Archivar"}</button>{row.archived_at && <button disabled={busy} onClick={() => void hardDelete(row)}>Eliminar definitivamente</button>}</div>{resource === "modelos" && !row.archived_at && <div><div className="admin-toolbar"><select value={relation[row.id] || ""} onChange={(e) => setRelation((current) => ({ ...current, [row.id]: e.target.value }))}><option value="">Añadir a desarrollo</option>{developments.filter((d) => d.developer === row.developer && !row.developments?.some((linked: any) => linked.id === d.id)).map((d) => <option value={d.id} key={d.id}>{d.name}</option>)}</select><button disabled={busy || !relation[row.id]} onClick={() => void addRelation(row)}>Relacionar</button></div>{row.developments?.map((linked: any) => <div className="admin-list-row" key={linked.link_id}><span>{linked.name}</span><button onClick={() => void removeRelation(linked.link_id)}>Desvincular</button></div>)}</div>}</td></tr>)}</AdminTable> : <div className="empty-state"><p>No hay registros.</p></div>}
  </AdminLayout>;
}

const permissionModuleLabels: Record<string, string> = { catalog: "Inventario", listings: "Publicación", crm: "CRM", content: "Contenido", analytics: "BI", marketing: "Marketing", audit: "Auditoría" };

function PermissionMatrix({ options, selected, onChange, details }: { options: any[]; selected: string[]; onChange: (keys: string[]) => void; details?: any[] }) {
  const grouped = options.reduce<Record<string, any[]>>((result, option) => { const moduleKey = option.module || option.key.split(".")[0]; (result[moduleKey] ||= []).push(option); return result; }, {});
  const groups = Object.entries(grouped);
  const toggle = (key: string, checked: boolean) => onChange(checked ? Array.from(new Set([...selected, key])) : selected.filter((item) => item !== key));
  return <div className="permission-matrix"><div className="table-actions"><button type="button" onClick={() => onChange(options.map((x) => x.key))}>Seleccionar todos</button><button type="button" onClick={() => onChange([])}>Quitar todos</button></div>{groups.map(([module, items]) => <section key={module}><div className="permission-group-title"><strong>{permissionModuleLabels[module] || module}</strong><button type="button" onClick={() => onChange(Array.from(new Set([...selected, ...items.map((x: any) => x.key)])))}>Seleccionar bloque</button></div>{items.map((permission: any) => { const detail = details?.find((item) => item.key === permission.key); const allowed = selected.includes(permission.key); return <label className="permission-row" key={permission.key}><input type="checkbox" checked={allowed} onChange={(e) => toggle(permission.key, e.target.checked)} /><span>{permission.name}</span><strong>{allowed ? "Permitido" : "Denegado"}</strong><small>{detail?.origin || "Definido por el rol"}</small></label>; })}</section>)}</div>;
}

function UserManagementPage() {
  const [rows, setRows] = useState<any[]>([]); const [roles, setRoles] = useState<any[]>([]); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<any>(); const [permissionOptions, setPermissionOptions] = useState<any[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ first_name: "", last_name: "", email: "", password: "", role_name: "Founder Admin" });
  const load = useCallback(async () => { const [users, roleRows] = await Promise.all([fetchAllPages<any>("/api/v1/admin/users/?page_size=100"), fetchAllPages<any>("/api/v1/admin/roles/?page_size=100")]); setRows(users); setRoles(roleRows.filter((role) => !role.is_owner)); }, []);
  useEffect(() => { Promise.all([fetchAllPages<any>("/api/v1/admin/users/?page_size=100"), fetchAllPages<any>("/api/v1/admin/roles/?page_size=100"), apiFetch<any[]>("/api/v1/admin/users/permission-options/")]).then(([users, roleRows, permissionRows]) => { setRows(users); setRoles(roleRows.filter((role) => !role.is_owner)); setPermissionOptions(permissionRows); }).catch((e) => setError(e.message)); }, []);
  const create = async () => { setBusy(true); setError(""); try { await apiFetch("/api/v1/admin/users/", { method: "POST", body: JSON.stringify(form) }); setCreating(false); setForm({ first_name: "", last_name: "", email: "", password: "", role_name: "Founder Admin" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible crear el usuario"); } finally { setBusy(false); } };
  const saveUser = async () => { if (!editing) return; setBusy(true); setError(""); try { await apiFetch(`/api/v1/admin/users/${editing.id}/`, { method: "PATCH", body: JSON.stringify({ first_name: editing.first_name, last_name: editing.last_name, email: editing.email, role_name: editing.role, is_active: editing.is_active, ...(editing.password ? { password: editing.password } : {}) }) }); await apiFetch(`/api/v1/admin/users/${editing.id}/permissions/`, { method: "POST", body: JSON.stringify({ permissions: editing.desired_permissions || [] }) }); setEditing(undefined); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar el usuario"); } finally { setBusy(false); } };
  const resetRole = async () => { if (!editing) return; const user = await apiFetch<any>(`/api/v1/admin/users/${editing.id}/reset-to-role/`, { method: "POST", body: "{}" }); setEditing({ ...user, password: "", desired_permissions: user.effective_permissions }); await load(); };
  const roleOptions = roles.map((role) => <option value={role.name} key={role.id}>{role.name === "Founder Admin" ? "Administrador general" : role.name}</option>);
  return <AdminLayout title="Usuarios"><div className="admin-title"><div><span className="eyebrow">Seguridad</span><h2>Usuarios</h2></div><button className="button" onClick={() => setCreating(true)}>Crear usuario</button></div>
    {creating && <section className="admin-panel"><h3>Nuevo usuario administrativo</h3><div className="admin-form-grid">{(["first_name", "last_name", "email", "password"] as const).map((key) => <label className="field" key={key}><span>{{ first_name: "Nombre", last_name: "Apellidos", email: "Correo", password: "Contraseña inicial" }[key]}</span><input type={key === "password" ? "password" : key === "email" ? "email" : "text"} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<label className="field"><span>Rol</span><select value={form.role_name} onChange={(e) => setForm({ ...form, role_name: e.target.value })}>{roleOptions}</select></label></div><div className="admin-form-actions"><button className="button secondary" onClick={() => setCreating(false)}>Cancelar</button><button className="button" disabled={busy} onClick={() => void create()}>Crear usuario</button></div></section>}
    {editing && <section className="admin-panel"><h3>Rol base + excepciones personales</h3><div className="admin-form-grid">{[["Nombre","first_name"],["Apellidos","last_name"],["Correo","email"]].map(([label,key]) => <label className="field" key={key}><span>{label}</span><input value={editing[key] || ""} onChange={(e) => setEditing({ ...editing, [key]: e.target.value })} /></label>)}<label className="field"><span>Rol base</span><select value={editing.role} onChange={(e) => setEditing({ ...editing, role: e.target.value })}>{roleOptions}</select></label></div><PermissionMatrix options={permissionOptions} selected={editing.desired_permissions || []} onChange={(keys) => setEditing({ ...editing, desired_permissions: keys })} details={editing.permission_details} /><div className="admin-form-actions"><button className="button secondary" onClick={() => void resetRole()}>Restablecer al rol</button><button className="button secondary" onClick={() => setEditing(undefined)}>Cancelar</button><button className="button" disabled={busy} onClick={() => void saveUser()}>Guardar accesos</button></div></section>}
    {error && <p className="form-error">{error}</p>}<AdminTable heads={["Nombre", "Correo", "Rol", "Activo", "Último acceso", "MFA", "Acciones"]}>{rows.map((user) => <tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{user.role_display}</td><td>{user.is_active ? "Sí" : "No"}</td><td>{user.last_login ? formatDate(user.last_login) : "—"}</td><td>{user.mfa_enabled ? "Configurado" : "Pendiente"}</td><td><button disabled={user.role === "Owner"} onClick={() => setEditing({ ...user, password: "", desired_permissions: [...user.effective_permissions] })}>Gestionar acceso</button></td></tr>)}</AdminTable>
  </AdminLayout>;
}

export function AdminRolesPage() {
  const [roles, setRoles] = useState<any[]>([]); const [permissions, setPermissions] = useState<any[]>([]); const [editing, setEditing] = useState<any>(); const [error, setError] = useState("");
  const load = useCallback(async () => { const [roleRows, permissionRows] = await Promise.all([fetchAllPages<any>("/api/v1/admin/roles/?page_size=100"), apiFetch<any[]>("/api/v1/admin/users/permission-options/")]); setRoles(roleRows); setPermissions(permissionRows); }, []);
  useEffect(() => { Promise.all([fetchAllPages<any>("/api/v1/admin/roles/?page_size=100"), apiFetch<any[]>("/api/v1/admin/users/permission-options/")]).then(([roleRows, permissionRows]) => { setRoles(roleRows); setPermissions(permissionRows); }).catch((e) => setError(e.message)); }, []);
  const save = async () => { try { await apiFetch(editing.id ? `/api/v1/admin/roles/${editing.id}/` : "/api/v1/admin/roles/", { method: editing.id ? "PATCH" : "POST", body: JSON.stringify({ name: editing.name, description: editing.description, permissions: editing.permission_keys }) }); setEditing(undefined); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar el rol"); } };
  const remove = async (role: any) => { if (!window.confirm(`Eliminar el rol ${role.name}?`)) return; try { await apiFetch(`/api/v1/admin/roles/${role.id}/`, { method: "DELETE" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible eliminar el rol"); } };
  return <AdminLayout title="Roles"><div className="admin-title"><div><span className="eyebrow">Seguridad</span><h2>Roles y permisos</h2></div><button className="button" onClick={() => setEditing({ name: "", description: "", permission_keys: [] })}>Crear rol</button></div>{error && <p className="form-error">{error}</p>}{editing && <section className="admin-panel"><div className="admin-form-grid"><label className="field"><span>Nombre</span><input value={editing.name} disabled={editing.is_owner} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></label><label className="field"><span>Descripción breve</span><input value={editing.description || ""} onChange={(e) => setEditing({ ...editing, description: e.target.value })} /></label></div><PermissionMatrix options={permissions} selected={editing.permission_keys || []} onChange={(keys) => setEditing({ ...editing, permission_keys: keys })} /><div className="admin-form-actions"><button className="button secondary" onClick={() => setEditing(undefined)}>Cancelar</button><button className="button" disabled={!editing.name || editing.is_owner} onClick={() => void save()}>Guardar rol</button></div></section>}<AdminTable heads={["Rol", "Descripción", "Usuarios", "Tipo", "Acciones"]}>{roles.map((role) => <tr key={role.id}><td>{role.name === "Founder Admin" ? "Administrador general" : role.name}</td><td>{role.description}</td><td>{role.user_count}</td><td>{role.is_owner ? "Reservado" : role.is_system ? "Sistema" : "Personalizado"}</td><td><div className="table-actions"><button disabled={role.is_owner} onClick={() => setEditing({ ...role })}>Editar</button><button disabled={role.is_system || role.user_count > 0} onClick={() => void remove(role)}>Eliminar</button></div></td></tr>)}</AdminTable></AdminLayout>;
}
