"use client";
import { useCallback, useEffect, useState } from "react";
import { AdminLayout } from "@/components/admin";
import { apiFetch, fetchAllPages } from "@/services/api";

type Kind = "privacy-notices" | "terms-of-use";
type Document = { id: string; version: string; title: string; body: string; status: "DRAFT" | "PUBLISHED" | "RETIRED"; content_hash: string; effective_at?: string; production_ready?: boolean };
export function LegalAdminPage() {
  const [kind, setKind] = useState<Kind>("privacy-notices"); const [items, setItems] = useState<Document[]>([]); const [draft, setDraft] = useState<Partial<Document>>({}); const [error, setError] = useState("");
  const load = useCallback(() => fetchAllPages<Document>(`/api/v1/admin/${kind}/?page_size=100`).then(setItems).catch((e) => setError(e.message)), [kind]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { setError(""); try { await apiFetch(draft.id ? `/api/v1/admin/${kind}/${draft.id}/` : `/api/v1/admin/${kind}/`, { method: draft.id ? "PATCH" : "POST", body: JSON.stringify({ version: draft.version, title: draft.title, body: draft.body, effective_at: draft.effective_at || null, production_ready: Boolean(draft.production_ready) }) }); setDraft({}); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible guardar."); } };
  const publish = async (item: Document) => { try { await apiFetch(`/api/v1/admin/${kind}/${item.id}/publish/`, { method: "POST", body: "{}" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible publicar."); } };
  const editable = !draft.id || draft.status === "DRAFT";
  return <AdminLayout title="Contenido legal"><div className="admin-panel"><h1>Legal</h1><label className="field"><span>Documento</span><select value={kind} onChange={(e) => { setKind(e.target.value as Kind); setDraft({}); }}><option value="privacy-notices">Aviso de Privacidad</option><option value="terms-of-use">Términos de Uso</option></select></label>{error && <p className="form-error">{error}</p>}<h2>{draft.id ? (editable ? "Editar borrador" : "Ver versión") : "Nuevo borrador"}</h2><label className="field"><span>Versión</span><input disabled={!editable} value={draft.version || ""} onChange={(e) => setDraft({ ...draft, version: e.target.value })} /></label><label className="field"><span>Título</span><input disabled={!editable} value={draft.title || ""} onChange={(e) => setDraft({ ...draft, title: e.target.value })} /></label><label className="field"><span>Contenido Markdown</span><textarea disabled={!editable} rows={18} value={draft.body || ""} onChange={(e) => setDraft({ ...draft, body: e.target.value })} /></label><label><input type="checkbox" disabled={!editable} checked={Boolean(draft.production_ready)} onChange={(e) => setDraft({ ...draft, production_ready: e.target.checked })} /> Revisado como documento integral vigente</label>{editable && <button className="button" onClick={() => void save()}>Guardar borrador</button>}<h3>Previsualización segura</h3><article style={{ whiteSpace: "pre-wrap" }}>{draft.body || "Selecciona o redacta un documento."}</article><h2>Historial</h2>{items.map((item) => <article key={item.id} className="admin-list-row"><div><strong>{item.version} · {item.title}</strong><small>{item.status} · {item.content_hash || "sin hash"}</small></div><div className="table-actions"><button onClick={() => setDraft(item)}>{item.status === "DRAFT" ? "Editar / previsualizar" : "Ver"}</button>{item.status === "DRAFT" && <button onClick={() => void publish(item)}>Publicar</button>}{item.status === "PUBLISHED" && <button onClick={() => setDraft({ version: `${item.version}-next`, title: item.title, body: item.body, status: "DRAFT", production_ready: false })}>Crear nueva versión</button>}</div></article>)}</div></AdminLayout>;
}
