# Generated by Django 6.1 on 2026-08-19 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyNoticeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=30, unique=True)),
                ('published_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('CONTACTED', 'Contactado'), ('INTERESTED', 'Interesado'), ('VISIT_SCHEDULED', 'Visita programada'), ('NEGOTIATING', 'Negociación'), ('WON', 'Ganado'), ('LOST', 'Perdido')], db_index=True, default='NEW', max_length=25)),
                ('first_source', models.CharField(blank=True, max_length=100, null=True)),
                ('last_source', models.CharField(blank=True, max_length=100, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_leads', 'Puede administrar clientes')],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WEB', 'Sitio web'), ('WHATSAPP', 'WhatsApp'), ('PHONE', 'Teléfono'), ('EMAIL', 'Correo'), ('SOCIAL', 'Red social'), ('MANUAL', 'Captura manual')], max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nueva'), ('VIEWED', 'Vista'), ('ATTENDED', 'Atendida')], default='NEW', max_length=15)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='listings.listing')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='crm.lead')),
            ],
            options={
                'permissions': [('manage_inquiries', 'Puede administrar consultas')],
            },
        ),
        migrations.CreateModel(
            name='LeadInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_type', models.CharField(choices=[('VIEWED', 'Vista'), ('FAVORITED', 'Favorita'), ('INQUIRED', 'Consultada'), ('VISITED', 'Visitada')], max_length=15)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='crm.lead')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_interests', to='catalog.propertyoffering')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('NEW', 'Nuevo'), ('CONTACTED', 'Contactado'), ('INTERESTED', 'Interesado'), ('VISIT_SCHEDULED', 'Visita programada'), ('NEGOTIATING', 'Negociación'), ('WON', 'Ganado'), ('LOST', 'Perdido')], max_length=25)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_history', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_id', models.UUIDField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=100)),
                ('granted', models.BooleanField()),
                ('granted_at', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='crm.lead')),
                ('privacy_notice_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.privacynoticeversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada')], default='CLOSED', max_length=15)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='crm.lead')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='listings.listing')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='catalog.propertyoffering')),
            ],
            options={
                'permissions': [('manage_sales', 'Puede administrar ventas')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('COMPLETED', 'Realizada'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No asistió')], default='SCHEDULED', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='crm.lead')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='catalog.propertyoffering')),
            ],
            options={
                'permissions': [('manage_visits', 'Puede administrar visitas')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'owner_user'], name='crm_lead_status_d0820a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-created_at'], name='crm_lead_created_deedb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadstagehistory',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('lead',), name='one_current_lead_stage'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='sale_price_nonnegative'),
        ),
    ]
