# Generated by Django 6.1 on 2026-08-21 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_propertyoffering_offering_bedrooms_max_nonnegative_and_more'),
        ('crm', '0001_initial'),
        ('listings', '0002_remove_pricerecord_on_request_has_no_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CLOSED', 'CANCELLED'])), name='sale_status_valid'),
        ),
    ]
