# Generated by Django 6.1 on 2026-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_sale_sale_status_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='intent',
            field=models.CharField(choices=[('INFORMATION', 'Solicitud de información'), ('VISIT_REQUEST', 'Solicitud de visita'), ('GENERAL_CONTACT', 'Contacto general')], db_index=True, default='INFORMATION', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(blank=True, choices=[('PROPERTY_INFORMATION', 'Información de una propiedad'), ('SEARCH_ASSISTANCE', 'Ayuda con mi búsqueda'), ('GENERAL_COMMENT', 'Comentario general')], max_length=30, null=True),
        ),
    ]
