# Generated by Django 6.1 on 2026-09-10 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_inquiry_intent_inquiry_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacynoticeversion',
            options={'permissions': [('publish_privacy_notice', 'Puede publicar avisos de privacidad')]},
        ),
        migrations.AddField(
            model_name='privacynoticeversion',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacynoticeversion',
            name='effective_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacynoticeversion',
            name='historical_content_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacynoticeversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privacynoticeversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('RETIRED', 'Retirada')], db_index=True, default='DRAFT', max_length=12),
        ),
        migrations.AddField(
            model_name='privacynoticeversion',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='privacynoticeversion',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='privacynoticeversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TermsOfUseVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('RETIRED', 'Retirada')], db_index=True, default='DRAFT', max_length=12)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('historical_content_available', models.BooleanField(default=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('publish_terms_of_use', 'Puede publicar términos de uso')],
            },
        ),
    ]
