#!/usr/bin/env bash
set -Eeuo pipefail
readonly ROOT="${CASAVIVA_ROOT:-/opt/casaviva}" PROJECT=casaviva
readonly REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-mx-central-1}}"
readonly IMAGE_SHA="${1:?Usage: first-install-pilot.sh IMAGE_SHA}"
[[ "$IMAGE_SHA" =~ ^[0-9a-f]{40}$ ]] || { echo "IMAGE_SHA must be a full immutable Git SHA" >&2; exit 2; }
exec 9>"$ROOT/deploy.lock"
flock -n 9 || { echo "Another deployment is running" >&2; exit 75; }
[[ ! -f "$ROOT/shared/first_install_complete" ]] || { echo "First install already completed; use deploy.sh" >&2; exit 2; }
ops="$ROOT/current-ops"
[[ -d "$ops" ]] || { echo "Install the versioned ops bundle first" >&2; exit 2; }
account_id="$(aws sts get-caller-identity --query Account --output text --region "$REGION")"
registry="$account_id.dkr.ecr.$REGION.amazonaws.com"
release="$ROOT/releases/$IMAGE_SHA"
mkdir -p "$release/docker/postgres"
install -m 0644 "$ops/docker-compose.production.yml" "$release/docker-compose.yml"
install -m 0644 "$ops/docker-compose.bootstrap.yml" "$release/docker-compose.bootstrap.yml"
install -m 0644 "$ops/docker/Caddyfile" "$release/docker/Caddyfile"
install -m 0644 "$ops/docker/Caddyfile.bootstrap" "$release/docker/Caddyfile.bootstrap"
install -m 0755 "$ops/docker/postgres/init-roles.sh" "$release/docker/postgres/init-roles.sh"
umask 077
parameters="$release/parameters.json"
aws ssm get-parameters-by-path --region "$REGION" --path /casaviva-pilot/ --with-decryption --recursive --output json > "$parameters"
python3 "$ops/scripts/render-pilot-env.py" --images-sha "$IMAGE_SHA" --registry "$registry" < "$parameters" > "$release/.env.production"
rm -f "$parameters"
compose=(docker compose -p "$PROJECT" --env-file "$release/.env.production" -f "$release/docker-compose.yml" -f "$release/docker-compose.bootstrap.yml")
aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$registry"
"${compose[@]}" config --quiet
"${compose[@]}" pull
"${compose[@]}" up -d --wait postgres
set -a
# shellcheck disable=SC1090 -- generated by render-pilot-env.py with shell-safe quoting.
source "$release/.env.production"
set +a
migrator_url="$MIGRATOR_DATABASE_URL"
app_url="$APP_DATABASE_URL"
[[ "$migrator_url" == postgresql://casaviva_migrator:* && "$app_url" == postgresql://casaviva_app:* ]] || { echo "Invalid database roles" >&2; exit 2; }
[[ "$BACKUP_DATABASE_URL" == postgresql://casaviva_backup:* && "$BACKUP_S3_URI" == s3://* ]] || { echo "Invalid backup configuration" >&2; exit 2; }
[[ -n "${PUBLIC_DOMAIN:-}" && "$PUBLIC_DOMAIN" != *://* ]] || { echo "PUBLIC_DOMAIN must be a hostname without scheme" >&2; exit 2; }
install -m 0600 /dev/null "$ROOT/shared/backup.env"
printf 'BACKUP_DATABASE_URL=%s\nBACKUP_S3_URI=%s\nAWS_REGION=%s\n' "$BACKUP_DATABASE_URL" "$BACKUP_S3_URI" "$REGION" > "$ROOT/shared/backup.env"
systemctl daemon-reload
systemctl enable --now casaviva-postgres-backup.timer
systemctl is-enabled --quiet casaviva-postgres-backup.timer
systemctl is-active --quiet casaviva-postgres-backup.timer
systemctl is-active --quiet amazon-cloudwatch-agent
"${compose[@]}" run --rm -e DATABASE_URL="$migrator_url" backend python manage.py migrate --noinput
"${compose[@]}" run --rm -e DATABASE_URL="$migrator_url" backend python manage.py harden_database_roles
"${compose[@]}" run --rm -e DATABASE_URL="$app_url" backend python manage.py seed_system
"${compose[@]}" up -d --remove-orphans --wait
actual_user="$("${compose[@]}" exec -T backend python manage.py shell -c 'from django.db import connection; connection.ensure_connection(); print(connection.connection.info.user)' | tail -1)"
[[ "$actual_user" == casaviva_app ]] || { echo "Runtime DB role is $actual_user" >&2; exit 1; }
curl --insecure --fail --silent --show-error https://127.0.0.1:8443/api/health/ready/ >/dev/null
printf '%s\n' "$IMAGE_SHA" > "$ROOT/shared/current_release"
printf '%s\n' "$IMAGE_SHA" > "$ROOT/shared/bootstrap_release"
ln -sfn "$release" "$ROOT/current"
echo "BOOTSTRAP_PRIVATE_READY: use SSM port forwarding to 127.0.0.1:8443; public ports remain closed."
echo "Configure founders/MFA/legal data, then run deploy.sh; it will require readiness PASS before enabling HTTPS."
