# Generated by Django 6.1 on 2026-08-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingcampaign',
            options={'permissions': [('view_campaigns', 'Puede consultar campañas'), ('manage_campaigns', 'Puede administrar campañas')]},
        ),
        migrations.AlterModelOptions(
            name='marketingspend',
            options={'permissions': [('view_spend', 'Puede consultar gasto de marketing'), ('manage_spend', 'Puede administrar gasto de marketing')]},
        ),
    ]
