# Generated by Django 6.1 on 2026-08-24 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_marketingcampaign_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingspend',
            name='is_voided',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='marketingspend',
            name='void_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketingspend',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingspend',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_marketing_spend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketingspend',
            name='currency',
            field=models.CharField(choices=[('MXN', 'MXN')], default='MXN', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='marketingspend',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'MXN')), name='marketing_spend_currency_mxn'),
        ),
        migrations.AddConstraint(
            model_name='marketingspend',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_voided', False), ('void_reason__isnull', True), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('is_voided', True), ('void_reason__isnull', False), ('voided_at__isnull', False), ('voided_by__isnull', False)), _connector='OR'), name='marketing_spend_void_consistent'),
        ),
    ]
