# Generated by Django 6.1 on 2026-08-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
